### ISSUE TITLE
authorizationUri cannot be empty (Spring Boot 2.3.0.M4)

### ISSUE THREAD

**Issue by dcoraboeuf** [okta/okta-spring-boot#170]
Hi,

I'm using:

* Spring Boot 2.3.0.M4
* Okta Boot Starter 1.4.0
* JDK11

I've declared the following configuration in `application.yml`:

```
okta:
  oauth2:
    issue: "https://<redacted>.okta.com/oauth2/default/"
    client-id: "<redacted>"
    client-secret: "<redacted>"
```

In my web security config:

```
override fun configure(http: HttpSecurity) {
      http {
            oauth2Client {  }
            oauth2Login {  }
     }
}
```

and the application cannot start because of:

```
Caused by: java.lang.IllegalArgumentException: authorizationUri cannot be empty
	at org.springframework.util.Assert.hasText(Assert.java:284)
	at org.springframework.security.oauth2.client.registration.ClientRegistration$Builder.validateAuthorizationCodeGrantType(ClientRegistration.java:572)
	at org.springframework.security.oauth2.client.registration.ClientRegistration$Builder.build(ClientRegistration.java:528)
	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.getClientRegistration(OAuth2ClientPropertiesRegistrationAdapter.java:73)
	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.lambda$getClientRegistrations$0(OAuth2ClientPropertiesRegistrationAdapter.java:53)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.getClientRegistrations(OAuth2ClientPropertiesRegistrationAdapter.java:52)
	at org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientRegistrationRepositoryConfiguration.clientRegistrationRepository(OAuth2ClientRegistrationRepositoryConfiguration.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
```

Any idea on the root cause of this error? I've followed the guidelines at https://github.com/okta/okta-spring-boot#supporting-server-side-applications---oauth-code-flow

Thanks for any help,
Damien

**Comment by mraible** [comment]
It looks like you misspelled `issuer` in your YAML configuration.

**Comment by dcoraboeuf** [comment]
OMG 😊 The longer I spend on an issue, the more stupid the root cause is...

Sorry about this then, and thanks for the typo correction

Best regards,
Damien
