### ISSUE TITLE
Issue Upgrading Spring Boot, Spring Cloud, and Okta Spring Boot Starter

### ISSUE THREAD

**Issue by adamcraftc** [okta/okta-spring-boot#211]
### Details:
We are using a Spring Boot application to validate PKCE tokens using the okta-spring-boot-starter SDK. If we upgrade to the latest Spring Boot, Spring Cloud, and Okta Spring Boot Starter versions, then we constantly get “Invalid Token” back.

**Working scenario:**
```xml
<parent>
                             <groupId>org.springframework.boot</groupId>
                             <artifactId>spring-boot-starter-parent</artifactId>
                             **<version>2.1.0.RELEASE</version>**
                             <relativePath /> <!-- lookup parent from repository -->
              </parent>
<dependencies>
                             <dependency>
                                           <groupId>org.springframework.boot</groupId>
                                           <artifactId>spring-boot-configuration-processor</artifactId>
                                           <optional>true</optional>
                             </dependency>
                             <!-- security - begin -->
                             <dependency>
                                           <groupId>org.springframework.boot</groupId>
                                           <artifactId>spring-boot-starter-security</artifactId>
                             </dependency>
                             <dependency>
                                           <groupId>org.springframework.cloud</groupId>
                                           <artifactId>spring-cloud-starter-oauth2</artifactId>
                             </dependency>
                            <dependency>
                                           <groupId>com.okta.spring</groupId>
                                           <artifactId>okta-spring-boot-starter</artifactId>
                                           **<version>0.6.1</version>**
                             </dependency>
                             <!-- security - end -->
                             <dependency>
                                           <groupId>org.springframework.cloud</groupId>
                                           <artifactId>spring-cloud-starter-netflix-zuul</artifactId>
                             </dependency>
                             <dependency>
                                           <groupId>com.auth0</groupId>
                                           <artifactId>java-jwt</artifactId>
                                           <version>3.10.3</version>
                             </dependency>
                             <dependency>
                                           <groupId>javax.ws.rs</groupId>
                                           <artifactId>javax.ws.rs-api</artifactId>
                                           <version>2.1.1</version>
                             </dependency>
                             <dependency>
                                           <groupId>org.springframework.retry</groupId>
                                           <artifactId>spring-retry</artifactId>
                             </dependency>
                             <dependency>
                                           <groupId>org.dom4j</groupId>
                                           <artifactId>dom4j</artifactId>
                                           <version>2.1.3</version>
                             </dependency>
                             <dependency>
                                           <groupId>org.bouncycastle</groupId>
                                           <artifactId>bcpkix-jdk15on</artifactId>
                                           <version>1.66</version>
                             </dependency>
              </dependencies>
              <dependencyManagement>
                             <dependencies>
                                           <dependency>
                                                         <groupId>org.springframework.cloud</groupId>
                                                          <artifactId>spring-cloud-dependencies</artifactId>
                                                          **<version>Greenwich.RELEASE</version>**
                                                          <type>pom</type>
                                                          <scope>import</scope>
                                           </dependency>
                             </dependencies>
              </dependencyManagement>
```

**Failing scenario (Preferred to Upgrade to):**
```xml
              <parent>
                             <groupId>org.springframework.boot</groupId>
                             <artifactId>spring-boot-starter-parent</artifactId>
                             **<version>2.3.4.RELEASE</version>**
                             <relativePath /> <!-- lookup parent from repository -->
              </parent>
<dependencies>
                             <dependency>
                                           <groupId>org.springframework.boot</groupId>
                                           <artifactId>spring-boot-configuration-processor</artifactId>
                                           <optional>true</optional>
                             </dependency>
                             <!-- security - begin -->
                             <dependency>
                                           <groupId>org.springframework.boot</groupId>
                                           <artifactId>spring-boot-starter-security</artifactId>
                             </dependency>
                             <dependency>
                                           <groupId>org.springframework.cloud</groupId>
                                           <artifactId>spring-cloud-starter-oauth2</artifactId>
                             </dependency>
                             <dependency>
                                           <groupId>com.okta.spring</groupId>
                                           <artifactId>okta-spring-boot-starter</artifactId>
                                           **<version>1.4.0</version>**
                             </dependency>
                             <!-- security - end -->
                             <dependency>
                                           <groupId>org.springframework.cloud</groupId>
                                           <artifactId>spring-cloud-starter-netflix-zuul</artifactId>
                             </dependency>
                             <dependency>
                                           <groupId>com.auth0</groupId>
                                           <artifactId>java-jwt</artifactId>
                                           <version>3.11.0</version>
                             </dependency>
                             <dependency>
                                           <groupId>javax.ws.rs</groupId>
                                           <artifactId>javax.ws.rs-api</artifactId>
                                           <version>2.1.1</version>
                             </dependency>
                             <dependency>
                                           <groupId>org.springframework.retry</groupId>
                                           <artifactId>spring-retry</artifactId>
                             </dependency>
                             <dependency>
                                           <groupId>org.dom4j</groupId>
                                           <artifactId>dom4j</artifactId>
                                           <version>2.1.3</version>
                             </dependency>
                             <dependency>
                                           <groupId>org.bouncycastle</groupId>
                                           <artifactId>bcpkix-jdk15on</artifactId>
                                           <version>1.66</version>
                             </dependency>
              </dependencies>
              <dependencyManagement>
                            <dependencies>
                                           <dependency>
                                                         <groupId>org.springframework.cloud</groupId>
                                                          <artifactId>spring-cloud-dependencies</artifactId>
                                                          **<version>Hoxton.SR8</version>**
                                                          <type>pom</type>
                                                          <scope>import</scope>
                                           </dependency>
                             </dependencies>
              </dependencyManagement>
```

**DEBUG LOG:**
```log
2020-10-22 13:47:33.149  INFO 24068 --- [           main] gov.hhs.cms.project.prime.Application       : Started Application in 12.715 seconds (JVM running for 13.232)
2020-10-22 13:47:38.994 DEBUG 24068 --- [o-7087-Acceptor] o.apache.tomcat.util.threads.LimitLatch  : Counting up[http-nio-7087-Acceptor] latch=1
2020-10-22 13:47:38.995 DEBUG 24068 --- [o-7087-Acceptor] o.apache.tomcat.util.threads.LimitLatch  : Counting up[http-nio-7087-Acceptor] latch=2
2020-10-22 13:47:39.027 DEBUG 24068 --- [nio-7087-exec-2] o.a.coyote.http11.Http11InputBuffer      : Before fill(): [true], parsingRequestLine: [true], parsingRequestLinePhase: [0], parsingRequestLineStart: [0], byteBuffer.position() [0]
2020-10-22 13:47:39.027 DEBUG 24068 --- [nio-7087-exec-1] o.a.coyote.http11.Http11InputBuffer      : Before fill(): [true], parsingRequestLine: [true], parsingRequestLinePhase: [0], parsingRequestLineStart: [0], byteBuffer.position() [0]
2020-10-22 13:47:39.027 DEBUG 24068 --- [nio-7087-exec-2] o.a.tomcat.util.net.SocketWrapperBase    : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@5c0e01fb:org.apache.tomcat.util.net.NioChannel@48dd3c84:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:7087 remote=/0:0:0:0:0:0:0:1:51799]], Read from buffer: [0]
2020-10-22 13:47:39.027 DEBUG 24068 --- [nio-7087-exec-1] o.a.tomcat.util.net.SocketWrapperBase    : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@6fce1e9e:org.apache.tomcat.util.net.NioChannel@36b26a38:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:7087 remote=/0:0:0:0:0:0:0:1:51798]], Read from buffer: [0]
2020-10-22 13:47:39.028 DEBUG 24068 --- [nio-7087-exec-2] org.apache.tomcat.util.net.NioEndpoint   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@5c0e01fb:org.apache.tomcat.util.net.NioChannel@48dd3c84:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:7087 remote=/0:0:0:0:0:0:0:1:51799]], Read direct from socket: [1158]
2020-10-22 13:47:39.028 DEBUG 24068 --- [nio-7087-exec-2] o.a.coyote.http11.Http11InputBuffer      : Received [GET /auth/user HTTP/1.1
Authorization: Bearer eyJraWQiOiJfanJiZ0xTaTdZc0hsQmR2SzlxVUl3TlVsYnhYR0JDVzZsdGx0R1Z3cXc0IiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULnJBNmxmV0JEdXV6aThoOTF0alBJNzRTanhTd0pDR2JUdHkzVVhtMExMd0EiLCJpc3MiOiJodHRwczovL25ld3dhdmVyYWR2Lm9rdGEuY29tL29hdXRoMi9hdXM3ODlqMnkwME5LZ2tDdDJwNyIsImF1ZCI6ImFwaTovL2RlZmF1bHQiLCJpYXQiOjE2MDMzOTE1MDMsImV4cCI6MTYwMzM5MjQwMywiY2lkIjoiMG9hNnU2MTI1eGlYUEJGdUQycDciLCJ1aWQiOiIwMHUxajlqaXVnS1lJQ1ZaSDJwNyIsInNjcCI6WyJlbWFpbCIsIm9wZW5pZCJdLCJzdWIiOiJwbGFuLXVzZXI5NkBERVYuQ01TLlJBRFZDREFULkNPTSJ9.DGRSuMpTmZwrk5iPWIr7kGgHW5PIWtWy0ilrNEIVcBeG1HCi6EEK1NQ4I9sq8-2yD67urQIdFu7fJWvR79GJEatJ4qUQV1IAUaLuBaxRQN3xFw7WkN-EwGlkKDe9jKl5--7PtqSq5aPYmOTEwREd9NaLmLyyTV9Z9n8KwdICNLrVF_8QV-Bf3lPj9YQ7JXdwjhYuTpGiB7VfoPH3WJdU9OMiRRTDx-o-OQ8PJ1lFrvIxFwMAMFJUgntU7YMPplst_wK4DtOavtX7fJ1p0mDmNaIMCVt4-7Rt_7m3afQDsYJu8lhfE2-sZnMNvVKf0O2e8C_jv8f9ZWyEmPIf-F_hQw
User-Agent: PostmanRuntime/7.26.5
Accept: */*
Cache-Control: no-cache
Postman-Token: 4ff61790-fcb6-43e3-91c5-28fa2bf9adec
Host: localhost:7087
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: JSESSIONID=A966DB5D76B007A592545ED060D6EC4F

]
2020-10-22 13:47:39.028 DEBUG 24068 --- [nio-7087-exec-1] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header

java.io.EOFException: null
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1231) ~[tomcat-embed-core-9.0.38.jar:9.0.38]
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1141) ~[tomcat-embed-core-9.0.38.jar:9.0.38]
        at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:791) ~[tomcat-embed-core-9.0.38.jar:9.0.38]
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:355) ~[tomcat-embed-core-9.0.38.jar:9.0.38]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261) ~[tomcat-embed-core-9.0.38.jar:9.0.38]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.38.jar:9.0.38]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-9.0.38.jar:9.0.38]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat-embed-core-9.0.38.jar:9.0.38]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.38.jar:9.0.38]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_241]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.38.jar:9.0.38]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_241]

2020-10-22 13:47:39.031 DEBUG 24068 --- [nio-7087-exec-1] o.apache.coyote.http11.Http11Processor   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@6fce1e9e:org.apache.tomcat.util.net.NioChannel@36b26a38:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:7087 remote=/0:0:0:0:0:0:0:1:51798]], Status in: [OPEN_READ], State out: [CLOSED]
2020-10-22 13:47:39.032 DEBUG 24068 --- [nio-7087-exec-1] o.apache.tomcat.util.threads.LimitLatch  : Counting down[http-nio-7087-exec-1] latch=2
2020-10-22 13:47:39.033 DEBUG 24068 --- [nio-7087-exec-1] org.apache.tomcat.util.net.NioEndpoint   : Calling [org.apache.tomcat.util.net.NioEndpoint@11256d8b].closeSocket([org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@6fce1e9e:org.apache.tomcat.util.net.NioChannel@36b26a38:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:7087 remote=/0:0:0:0:0:0:0:1:51798]])
2020-10-22 13:47:39.049 DEBUG 24068 --- [nio-7087-exec-2] org.apache.tomcat.util.http.Parameters   : Set query string encoding to UTF-8
2020-10-22 13:47:39.053 DEBUG 24068 --- [nio-7087-exec-2] o.a.t.util.http.Rfc6265CookieProcessor   : Cookies: Parsing b[]: JSESSIONID=A966DB5D76B007A592545ED060D6EC4F
2020-10-22 13:47:39.055 DEBUG 24068 --- [nio-7087-exec-2] o.a.catalina.connector.CoyoteAdapter     :  Requested cookie session id is A966DB5D76B007A592545ED060D6EC4F
2020-10-22 13:47:39.057 DEBUG 24068 --- [nio-7087-exec-2] o.a.c.authenticator.AuthenticatorBase    : Security checking request GET /auth/user
2020-10-22 13:47:39.057 DEBUG 24068 --- [nio-7087-exec-2] org.apache.catalina.realm.RealmBase      :   No applicable constraints defined
2020-10-22 13:47:39.060 DEBUG 24068 --- [nio-7087-exec-2] o.a.c.a.jaspic.AuthConfigFactoryImpl     : Loading persistent provider registrations from [C:\Users\adam.craft\AppData\Local\Temp\tomcat.4240949039889313372.7087\conf\jaspic-providers.xml]
2020-10-22 13:47:39.060 DEBUG 24068 --- [nio-7087-exec-2] o.a.c.authenticator.AuthenticatorBase    : Not subject to any constraint
2020-10-22 13:47:39.063  INFO 24068 --- [nio-7087-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-10-22 13:47:39.064  INFO 24068 --- [nio-7087-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-10-22 13:47:39.064 DEBUG 24068 --- [nio-7087-exec-2] o.s.web.servlet.DispatcherServlet        : Detected StandardServletMultipartResolver
2020-10-22 13:47:39.073 DEBUG 24068 --- [nio-7087-exec-2] o.s.web.servlet.DispatcherServlet        : enableLoggingRequestDetails='false': request parameters and headers will be masked to prevent unsafe logging of potentially sensitive data
2020-10-22 13:47:39.074  INFO 24068 --- [nio-7087-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 10 ms
2020-10-22 13:47:39.084 DEBUG 24068 --- [nio-7087-exec-2] o.s.security.web.FilterChainProxy        : /auth/user at position 1 of 16 in additional filter chain; firing Filter: 'WebAsyncManagerIntegrationFilter'
2020-10-22 13:47:39.087 DEBUG 24068 --- [nio-7087-exec-2] o.s.security.web.FilterChainProxy        : /auth/user at position 2 of 16 in additional filter chain; firing Filter: 'SecurityContextPersistenceFilter'
2020-10-22 13:47:39.089 DEBUG 24068 --- [nio-7087-exec-2] o.s.security.web.FilterChainProxy        : /auth/user at position 3 of 16 in additional filter chain; firing Filter: 'HeaderWriterFilter'
2020-10-22 13:47:39.091 DEBUG 24068 --- [nio-7087-exec-2] o.s.security.web.FilterChainProxy        : /auth/user at position 4 of 16 in additional filter chain; firing Filter: 'LogoutFilter'
2020-10-22 13:47:39.091 DEBUG 24068 --- [nio-7087-exec-2] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', GET]
2020-10-22 13:47:39.092 DEBUG 24068 --- [nio-7087-exec-2] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/auth/user'; against '/logout'
2020-10-22 13:47:39.092 DEBUG 24068 --- [nio-7087-exec-2] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', POST]
2020-10-22 13:47:39.092 DEBUG 24068 --- [nio-7087-exec-2] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /auth/user' doesn't match 'POST /logout'
2020-10-22 13:47:39.092 DEBUG 24068 --- [nio-7087-exec-2] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', PUT]
2020-10-22 13:47:39.093 DEBUG 24068 --- [nio-7087-exec-2] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /auth/user' doesn't match 'PUT /logout'
2020-10-22 13:47:39.093 DEBUG 24068 --- [nio-7087-exec-2] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', DELETE]
2020-10-22 13:47:39.093 DEBUG 24068 --- [nio-7087-exec-2] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /auth/user' doesn't match 'DELETE /logout'
2020-10-22 13:47:39.093 DEBUG 24068 --- [nio-7087-exec-2] o.s.s.web.util.matcher.OrRequestMatcher  : No matches found
2020-10-22 13:47:39.094 DEBUG 24068 --- [nio-7087-exec-2] o.s.security.web.FilterChainProxy        : /auth/user at position 5 of 16 in additional filter chain; firing Filter: 'OAuth2AuthorizationRequestRedirectFilter'
2020-10-22 13:47:39.094 DEBUG 24068 --- [nio-7087-exec-2] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/auth/user'; against '/oauth2/authorization/{registrationId}'
2020-10-22 13:47:39.095 DEBUG 24068 --- [nio-7087-exec-2] org.apache.tomcat.util.http.Parameters   : Set encoding to UTF-8
2020-10-22 13:47:39.095 DEBUG 24068 --- [nio-7087-exec-2] o.s.security.web.FilterChainProxy        : /auth/user at position 6 of 16 in additional filter chain; firing Filter: 'OAuth2AuthenticationProcessingFilter'
2020-10-22 13:47:39.099 DEBUG 24068 --- [nio-7087-exec-2] p.a.OAuth2AuthenticationProcessingFilter : Authentication request failed: error="invalid_token", error_description="Invalid access token: eyJraWQiOiJfanJiZ0xTaTdZc0hsQmR2SzlxVUl3TlVsYnhYR0JDVzZsdGx0R1Z3cXc0IiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULnJBNmxmV0JEdXV6aThoOTF0alBJNzRTanhTd0pDR2JUdHkzVVhtMExMd0EiLCJpc3MiOiJodHRwczovL25ld3dhdmVyYWR2Lm9rdGEuY29tL29hdXRoMi9hdXM3ODlqMnkwME5LZ2tDdDJwNyIsImF1ZCI6ImFwaTovL2RlZmF1bHQiLCJpYXQiOjE2MDMzOTE1MDMsImV4cCI6MTYwMzM5MjQwMywiY2lkIjoiMG9hNnU2MTI1eGlYUEJGdUQycDciLCJ1aWQiOiIwMHUxajlqaXVnS1lJQ1ZaSDJwNyIsInNjcCI6WyJlbWFpbCIsIm9wZW5pZCJdLCJzdWIiOiJwbGFuLXVzZXI5NkBERVYuQ01TLlJBRFZDREFULkNPTSJ9.DGRSuMpTmZwrk5iPWIr7kGgHW5PIWtWy0ilrNEIVcBeG1HCi6EEK1NQ4I9sq8-2yD67urQIdFu7fJWvR79GJEatJ4qUQV1IAUaLuBaxRQN3xFw7WkN-EwGlkKDe9jKl5--7PtqSq5aPYmOTEwREd9NaLmLyyTV9Z9n8KwdICNLrVF_8QV-Bf3lPj9YQ7JXdwjhYuTpGiB7VfoPH3WJdU9OMiRRTDx-o-OQ8PJ1lFrvIxFwMAMFJUgntU7YMPplst_wK4DtOavtX7fJ1p0mDmNaIMCVt4-7Rt_7m3afQDsYJu8lhfE2-sZnMNvVKf0O2e8C_jv8f9ZWyEmPIf-F_hQw"
2020-10-22 13:47:39.145 DEBUG 24068 --- [nio-7087-exec-2] o.s.s.w.header.writers.HstsHeaderWriter  : Not injecting HSTS header since it did not match the requestMatcher org.springframework.security.web.header.writers.HstsHeaderWriter$SecureRequestMatcher@3aebd93d
2020-10-22 13:47:39.149 DEBUG 24068 --- [nio-7087-exec-2] s.s.o.p.e.DefaultOAuth2ExceptionRenderer : Written [error="invalid_token", error_description="Invalid access token: eyJraWQiOiJfanJiZ0xTaTdZc0hsQmR2SzlxVUl3TlVsYnhYR0JDVzZsdGx0R1Z3cXc0IiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULnJBNmxmV0JEdXV6aThoOTF0alBJNzRTanhTd0pDR2JUdHkzVVhtMExMd0EiLCJpc3MiOiJodHRwczovL25ld3dhdmVyYWR2Lm9rdGEuY29tL29hdXRoMi9hdXM3ODlqMnkwME5LZ2tDdDJwNyIsImF1ZCI6ImFwaTovL2RlZmF1bHQiLCJpYXQiOjE2MDMzOTE1MDMsImV4cCI6MTYwMzM5MjQwMywiY2lkIjoiMG9hNnU2MTI1eGlYUEJGdUQycDciLCJ1aWQiOiIwMHUxajlqaXVnS1lJQ1ZaSDJwNyIsInNjcCI6WyJlbWFpbCIsIm9wZW5pZCJdLCJzdWIiOiJwbGFuLXVzZXI5NkBERVYuQ01TLlJBRFZDREFULkNPTSJ9.DGRSuMpTmZwrk5iPWIr7kGgHW5PIWtWy0ilrNEIVcBeG1HCi6EEK1NQ4I9sq8-2yD67urQIdFu7fJWvR79GJEatJ4qUQV1IAUaLuBaxRQN3xFw7WkN-EwGlkKDe9jKl5--7PtqSq5aPYmOTEwREd9NaLmLyyTV9Z9n8KwdICNLrVF_8QV-Bf3lPj9YQ7JXdwjhYuTpGiB7VfoPH3WJdU9OMiRRTDx-o-OQ8PJ1lFrvIxFwMAMFJUgntU7YMPplst_wK4DtOavtX7fJ1p0mDmNaIMCVt4-7Rt_7m3afQDsYJu8lhfE2-sZnMNvVKf0O2e8C_jv8f9ZWyEmPIf-F_hQw"] as "application/json" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@2da34c3]
2020-10-22 13:47:39.150 DEBUG 24068 --- [nio-7087-exec-2] s.s.w.c.SecurityContextPersistenceFilter : SecurityContextHolder now cleared, as request processing completed
2020-10-22 13:47:39.154 DEBUG 24068 --- [nio-7087-exec-2] o.a.coyote.http11.Http11InputBuffer      : Before fill(): [true], parsingRequestLine: [true], parsingRequestLinePhase: [0], parsingRequestLineStart: [0], byteBuffer.position() [0]
2020-10-22 13:47:39.155 DEBUG 24068 --- [nio-7087-exec-2] o.a.tomcat.util.net.SocketWrapperBase    : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@5c0e01fb:org.apache.tomcat.util.net.NioChannel@48dd3c84:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:7087 remote=/0:0:0:0:0:0:0:1:51799]], Read from buffer: [0]
2020-10-22 13:47:39.156 DEBUG 24068 --- [nio-7087-exec-2] org.apache.tomcat.util.net.NioEndpoint   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@5c0e01fb:org.apache.tomcat.util.net.NioChannel@48dd3c84:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:7087 remote=/0:0:0:0:0:0:0:1:51799]], Read direct from socket: [0]
2020-10-22 13:47:39.156 DEBUG 24068 --- [nio-7087-exec-2] o.a.coyote.http11.Http11InputBuffer      : Received []
2020-10-22 13:47:39.157 DEBUG 24068 --- [nio-7087-exec-2] o.apache.coyote.http11.Http11Processor   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@5c0e01fb:org.apache.tomcat.util.net.NioChannel@48dd3c84:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:7087 remote=/0:0:0:0:0:0:0:1:51799]], Status in: [OPEN_READ], State out: [OPEN]
2020-10-22 13:47:39.157 DEBUG 24068 --- [nio-7087-exec-2] org.apache.tomcat.util.net.NioEndpoint   : Registered read interest for [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@5c0e01fb:org.apache.tomcat.util.net.NioChannel@48dd3c84:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:7087 remote=/0:0:0:0:0:0:0:1:51799]]
2020-10-22 13:48:29.526 DEBUG 24068 --- [alina-utility-2] org.apache.catalina.session.ManagerBase  : Start expire sessions StandardManager at 1603392509525 sessioncount 0
2020-10-22 13:48:29.526 DEBUG 24068 --- [alina-utility-2] org.apache.catalina.session.ManagerBase  : End expire sessions StandardManager processingTime 1 expired sessions: 0
2020-10-22 13:48:39.188 DEBUG 24068 --- [nio-7087-exec-3] o.apache.tomcat.util.threads.LimitLatch  : Counting down[http-nio-7087-exec-3] latch=1
2020-10-22 13:48:39.189 DEBUG 24068 --- [nio-7087-exec-3] org.apache.tomcat.util.net.NioEndpoint   : Calling [org.apache.tomcat.util.net.NioEndpoint@11256d8b].closeSocket([org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@5c0e01fb:org.apache.tomcat.util.net.NioChannel@48dd3c84:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:7087 remote=/0:0:0:0:0:0:0:1:51799]])
```

**Comment by arvindkrishnakumar-okta** [comment]
@adamcraftc Thanks for reaching out!

To help me understand more, can you please tell me how you obtain the access token?

**Comment by adamcraftc** [comment]
@arvindkrishnakumar-okta We have our UI configured using the Okta Single Sign On widget for PKCE which calls directly to Okta to retrieve the token. This is the token that we are trying to authenticate on the backend application for API calls.

**Comment by arvindkrishnakumar-okta** [comment]
@adamcraftc There are a lot of major changes introduced between 0.6.1 -> 1.4.0. I need to look at your back-end application configuration (especially how you have configured your token validation). Can you provide more info on this?

**Comment by bdemers** [comment]
Hey @adamcraftc 
With the info at hand, I cannot spot the problem, I know there were a few things that changed between versions of Spring Security (specifically the OAuth module was re-written).  The Okta Spring Boot Starter just sits on top of Spring Security.
Because of this, there were some changes to Spring Cloud Gateway, I'm not sure if those effected Zuul or not.

Can you create a simplified example that reproduces the issue and stick it on GitHub?

Also, it looks like you have two JWT parsers on your classpath, Nimbus (from Spring Security), and Auth0.  Do you have a custom `JWTDecoder` bean?

**Comment by adamcraftc** [comment]
[Uploading demo.zip…]()
This demo application presents the issue where we receive the Invalid Token notification. 

If we change the pom.xml to the following rolled back versions, then it will work.
[working.pom.xml.txt](https://github.com/okta/okta-spring-boot/files/5494967/working.pom.xml.txt)

NOTE: Masked the Issuer and ClientId in application.properties


To test, I ran the endpoint http://localhost:7086/demo/data using Postman passing in the Authorization header with my PKCE Bearer token.

**Comment by bdemers** [comment]
@adamcraftc very helpful!  I should have noticed this when you first posted your pom files (sorry about that)

You have both the new and old Spring Security OAuth libraries on your classpath and that is causing the problem.  The new version is a rewrite and many things have changed, annotations, packages etc.

I put your demo project in a repo, and I added a commit that fixes the problem (hopefully with enough comments that you can see what I changed)
https://github.com/bdemers/okta-spring-boot-migration-demo/commit/f3f4b1684117a288030e4e69cdc6c4b065c2b050

Keep us posted!

**Comment by adamcraftc** [comment]
@bdemers Thank you for your support! That was our issue and we have been able to use this to resolve our issue.

**Comment by bdemers** [comment]
Thanks for following up @adamcraftc !
