### ISSUE TITLE
Facing issue on springboot okta in weblogic server

### ISSUE THREAD

**Issue by smworld30** [okta/okta-spring-boot#255]
For spring-boot 2.4.2 with okta-spring-boot-starter 2.0.0 ,not able to deploy the application in weblogic where as tomcat/jboss deployment is fine.
In weblogic facing below issue. Request help on this

I have raised one case in the below repository. 

https://github.com/okta/samples-java-spring/issues/88

They suggested me to contact support@okta.com . Is this place is same?

Caused By: java.lang.IllegalArgumentException: class com.okta.spring.boot.oauth.env.OktaOAuth2PropertiesMappingEnvironmentPostProcessor is not assignable to interface org.springframework.boot.env.EnvironmentPostProcessor
	at org.springframework.util.Assert.assignableCheckFailed(Assert.java:720)
	at org.springframework.util.Assert.isAssignable(Assert.java:651)
	at org.springframework.util.Assert.isAssignable(Assert.java:682)
	at org.springframework.boot.util.Instantiator.instantiate(Instantiator.java:99)
	at org.springframework.boot.util.Instantiator.instantiate(Instantiator.java:90)
	Truncated. see log file for complete stacktrace

**Comment by sergiishamrai-okta** [comment]
This issue is duplicating [samples-java-spring/88](https://github.com/okta/samples-java-spring/issues/88). Please reach out to customer support at support@okta.com for further assistance on this case. In case you have a related bug report, please keep it posted in the origin issue thread.
